### ISSUE TITLE
Add SSL to the library

### ISSUE THREAD

**Issue by StijnSimons** [StijnSimons/LWSL#3]
**Is your feature request related to a problem? Please describe.**
Yes; traffic is not encrypted when a packet is sent / received.

**Describe the solution you'd like**
Add SSL configuration to the library.

**Describe alternatives you've considered**
None.

**Comment by arankin-irl** [comment]
I'll have a look into this, but might first do a small PR to add some basic tests, then expand those with SSL related tests.

**Comment by StijnSimons** [comment]
> I'll have a look into this, but might first do a small PR to add some basic tests, then expand those with SSL related tests.

Alright, thanks. I'll check the PR once it comes out.

**Comment by arankin-irl** [comment]
Added the PR for basic secure socket server/client here: https://github.com/StijnSimons/LWSL/pull/5

I'll put in another PR in a little while with a utility class for creating the SSLContext.

**Comment by StijnSimons** [comment]
Thanks a bunch already! Merging the PR.
